# Node.js 尝试捕捉

> 原文：<https://www.tutorialkart.com/nodejs/node-js-try-catch/>

## Node.js 尝试捕捉

**Node.js Try Catch** 是一种错误处理机制。当一段代码预计会抛出错误并被 try 包围时，这段代码中抛出的任何异常都可以在 catch 块中处理。如果错误没有以任何方式处理，程序会突然终止，这不是一件好事。

注意:只对同步操作使用 **Node.js Try Catch** 是一个很好的实践。我们还将在本教程中了解为什么 **Try Catch** 不应该用于异步操作。

*   [node . js 的示例](#Example)Try Catch
*   [为什么 Node.js Try Catch 不应用于捕获异步操作中的错误](#Try-Catch-Not-For-Asynchronous-Operations)
*   [异步代码中的异常会怎么样？](#exceptions-in-asynchronous-code)

[![](img/925da31b32d6bc3827932f6c8afb11bb.png)](https://www.tutorialkart.com/)